export const LOAD_PRODUCTS = "LOAD_PRODUCTS";
export const SET_PRODUCTS = "SET_PRODUCTS";
export const SET_USER = "SET_USER";
export const LOGIN = "LOGIN";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const RESET_LOGIN_ERROR = "RESET_LOGIN_ERROR";
export const SET_FILTER = "SET_FILTER";
export const SET_FILTERD_PRODUCTS = "SET_FILTERD_PRODUCTS";
export const SET_LOADING = "SET_LOADING";
export const SET_IMPORT_RESULTS = "SET_IMPORT_RESULTS";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const DELETE_PRODUCT_CONFIRM = "DELETE_PRODUCT_CONFIRM";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_CANCEL = 'DELETE_PRODUCT_CANCEL';

